site_name: IvanK public knowledge base
site_url: https://ivankatliarchuk.github.io/
site_description: My technical knowledge collection is here.
site_author: Ivan K

# Repository
repo_name: 'GitHub'
edit_uri: ""
repo_url: https://github.com/ivankatliarchuk/knowledge-base

# Copyright
copyright: '&copy; 2021 ivanka'

# Configuration
docs_dir: 'docs'
theme:
  name: material
  language: en
  palette:
    # primary: 'light blue' # Used as the main color for the site top bar,
                          # links, etc...
    accent: 'deep orange' # Used as the highlight color for the site
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - tabs
    - tags
    # - toc.integrate

# Extensions
markdown_extensions:
  - meta
  - admonition
  - markdown.extensions.tables
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.pathconverter
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.progressbar
  - pymdownx.tabbed
  - toc:
      permalink: "#"

plugins:
  - search:
      prebuild_index: true
      lang:
      - en
  - awesome-pages:
      collapse_single_pages: true
  - autolinks
  # - pdf-export
  # - git-revision-date
  # - same-dir
  # - literate-nav:
  #     nav_file: SUMMARY.md
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true

# Customization
extra:
  manifest: 'manifest.json'
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/ivankatliarchuk'
    - icon: fontawesome/brands/linkedin
      link: 'https://github.com/ivankatliarchuk'
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/cloudkats
    - icon: fontawesome/brands/hackerrank
      link: https://www.hackerrank.com/tanzwud

nav:
  - Home:
    - index.md
    - quicklinks.md
    - awesome-pages.md
  - Blogs&Articles:
    - ... | blogs/*.md
  - Education:
    - ... | education/*.md
    - ... | workshops/*.md
  - Management:
    - Product:
      - ... | management/product/*.md
    - People:
      - ... | management/people/*.md
  - Devops & SRE:
    - ... | devops/*.md
    - Run Books:
      - ... | devops/run-books/*.md
    - Readiness Lists:
      - ... | devops/check-lists/*.md
    - Architecture Notes:
      - ... | devops/architecture-notes/*.md
    - Infrastructure:
      - ... | devops/infrastructure/*.md
    - Docs Examples:
      - ... | devops/examples/*.md
  - Tools:
    - tools/index.md
    - ... | tools/*.md
  - Properties&Travel:
    - idex.md
