name: changelog
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate changelog
        id: changelog
        uses: saadmk11/changelog-ci@v0.7.0
        with:
          changelog_filename: CHANGELOG.md
          committer_username:  'github-action'
          committer_email:  'github-action@github.com'

      # - name: Get the changelog
      #   run: echo "${{ steps.changelog.outputs.changelog }}"
