name: changelog

on:
  # push:
  #   branches:
  #     - master
  #   paths-ignore:
  #   - "README.md"
  #   - "CHANGELOG.md"
  #   - "renovate.json"
  # pull_request:
  #   types: [opened, reopened]
  #   paths-ignore:
  #   - "README.md"
  #   - "CHANGELOG.md"
  #   - "renovate.json"
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual trigger'
  # release:
  #   types: # This configuration does not affect the page_build event above
  #   - created

env:
  isForkedRepository: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}


jobs:
  changelog:
    runs-on: ubuntu-latest
    name: update changelog
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 30
          submodules: 'true'

      - name: Generate changelog
        id: changelog
        uses: saadmk11/changelog-ci@master
        with:
          changelog_filename: CHANGELOG.md
          committer_username: 'github-action'
          committer_email: 'github-action@github.com'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Get the changelog
      #   run: echo "${{ steps.changelog.outputs.changelog }}"

# https://github.com/saadmk11/changelog-ci
