name: changelog
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the changelog
        run: echo "${{ steps.changelog.outputs.changelog }}"
