name: governane.link-checker

# Run action on pull request event
on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:
    types: [opened, edited]
  schedule:
  - cron: "0 9 * * *"
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual trigger'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    # checkout to latest commit
    - uses: actions/checkout@master
    # run markdown linter
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
    # todo https://github.com/peter-evans/link-checker
