name: pull-request-test
on: pull_request

env:
  PYTHON_VERSION: "3.10"

jobs:
  build-on-merge-request:
    name: build-on-merge-request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip -V

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - run: mkdocs build --config-file ./mkdocs.yml
