name: create-release

on:
  push:
    branches:
    - master
    paths-ignore:
    - "README.md"
    - "CHANGELOG.md"
    - "renovate.json"

env:
  INITIAL_VERSION: 0.0.0
  WITH_V: true
  DEFAULT_BUMP: patch

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip')"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.22.0
      id: tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: release-drafter/release-drafter@v5
      with:
        publish: true
        prerelease: false
        commitish: ${{ github.ref }}
        tag: ${{ steps.tag.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
