name: create-release

on:
  push:
    branches:
    - master
    paths-ignore:
    - "README.md"
    - "CHANGELOG.md"
    - "renovate.json"

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
