name: lighthouse
on:
  workflow_dispatch:
  push:
    branches: [$default-branch, gh-pages]
  pull_request:
    branches: [$default-branch, gh-pages]
  schedule:
    - cron: '0 10 * * 2'
  pull_request:
    types: [opened,assigned,synchronize]

env:
  ENDPOIND: https://ivankatliarchuk.github.io/knowledge-base

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: run lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          tag: GitHub Action
          urls: ${{ env.ENDPOIND }}
          sha: ${{ github.sha }}
          branch: ${{ github.ref }}
          author: ${{ github.actor }}

      - name: handle lighthouse check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "90"
          minBestPracticesScore: "50"
          minPerformanceScore: "50"
          minProgressiveWebAppScore: "50"
          minSeoScore: "50"
