name: lighthouse
on:
  workflow_dispatch:
  push:
    branches: [$default-branch, gh-pages]
  pull_request:
    branches: [$default-branch, gh-pages]
    types: [opened,assigned,synchronize]
  schedule:
    - cron: '0 10 * * 2'

env:
  ENDPOIND: https://ivankatliarchuk.github.io/knowledge-base
  TEMPLATE: .github/templates/lighthouse.md

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: run lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          tag: GitHub Action
          urls: ${{ env.ENDPOIND }}
          sha: ${{ github.sha }}
          branch: ${{ github.ref }}
          author: ${{ github.actor }}

      - name: handle lighthouse check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "90"
          minBestPracticesScore: "50"
          minPerformanceScore: "50"
          minProgressiveWebAppScore: "50"
          minSeoScore: "50"

      - name: read file
        run: |
          echo "${{ toJSON(steps.lighthouseCheck.outputs) }}"
          echo "${{ steps.lighthouseCheck.outputs.lighthouseCheckResults.data.scores }}"
          echo "${{ steps.lighthouseCheck.outputs.lighthouseCheckResults.data.url }}"

      # https://github.com/JasonEtco/actions-toolkit#toolscontext
      - name: create issue from file
        uses: JasonEtco/create-an-issue@v2.5.0
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCORE: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults.scores }}
          URL: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults.url }}
          TITLE: 'Lighthosue performance'
        with:
          filename: ${{ env.TEMPLATE }}
          assignees: ${{ github.actor }}
          update_existing: true

      - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
      - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
