name: scan.owasp-zaproxy-full

on:
  workflow_dispatch:
  push:
    branches: [  $default-branch, gh-pages ]

  schedule:
    - cron: '0 10 * * 0'

env:
  ENDPOIND: https://ivankatliarchuk.github.io/knowledge-base

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan fully the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ env.ENDPOIND }}
          # rules_file_name: '.zap/rules.tsv'
          # cmd_options: '-a'
